PLAT-9622 Default kubernetes_version to 1.34 (#114)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -135,7 +135,13 @@ jobs:
           name: "Set module source to latest domino release"
           working_directory: tests
           command: |
-            latest_tag="v2.5.0"
+            latest_tag=$(git -c 'versionsort.suffix=-' ls-remote --tags --refs --sort=-v:refname \
+              "https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" 'v*.*.*' \
+              | head -1 | awk -F/ '{print $NF}')
+            if [ -z "$latest_tag" ]; then
+              echo "Failed to resolve latest release tag"
+              exit 1
+            fi
             export MOD_SOURCE="github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git?ref=${latest_tag}"
             echo "Latest published release tag is: ${latest_tag}"
             echo "Setting module source to: ${MOD_SOURCE}"
